### ISSUE TITLE
Improve I2C Speed

### ISSUE THREAD

**Issue by hallard** [sparkfun/SparkFun_Micro_OLED_Particle_Library#2]
Just tried this lib on photon, works fine, I used a cheap ebay SSD1306 128x64 Oled without any issue.

As SSD1306 spec says it can works until 400 KHz in I2C mode, I suggest to add the following line in the `i2csetup()` just before `Wire.begin();`

`Wire.setSpeed(CLOCK_SPEED_400KHZ);`

this becomes 

```
void MicroOLED::i2cSetup()
{
Wire.setSpeed(CLOCK_SPEED_400KHZ);
Wire.begin();

// SCL frequency = (F_CPU) / (16 + 2(TWBR) * (prescalar))
//TWBR = ((F_CPU / I2C_FREQ) - 16) / 2;
}
```

For information I was able to push my OLED until 1 MHz I2C, just 10 x faster than original code by using `Wire.setSpeed(1000000);` instead of `Wire.setSpeed(CLOCK_SPEED_400KHZ);`
Worth it

**Comment by jimblom** [comment]
Great catch! I've added a `Wire.setSpeed` declaration in the [latest commit](https://github.com/sparkfun/SparkFun_Micro_OLED_Particle_Library/commit/2e8a37d97767c74a208d997125fbd994613ab017). 

Also a couple other I2C bug fixes in there. Tests out on the Photon OLED shield.
