### ISSUE TITLE
OLED-CUBE sample doesn't build in Particle Build (aka Web IDE)

### ISSUE THREAD

**Issue by ScruffR** [sparkfun/SparkFun_Micro_OLED_Particle_Library#3]
Due to `#include "application.h"` in `SparkFunMicroOLED.h` the IDE throws `oled-cube.cpp:39:80: fatal error: SparkFunMicroOLED/SparkFunMicroOLED.h: No such file or directory
 #include "application.h"`

**Comment by jimblom** [comment]
Is this still a problem on your end?

I'm not getting any errors in the Build IDE after clicking the "Use this example" button and compiling.

**Comment by ScruffR** [comment]
Hmm! No, no issues anymore - strange :sunglasses:

**Comment by jimblom** [comment]
Cool. Closing this up. Thanks!

**Comment by mat01** [comment]
Guys - I'm getting exactly the same problem. The example code works fine, my code does not. Have tried using both <> and "" for the library import statement.
