### ISSUE TITLE
File not found when used in Particle Web IDE

### ISSUE THREAD

**Issue by mat01** [sparkfun/SparkFun_Micro_OLED_Particle_Library#9]
Error message is : 

test.ino:2:62: SparkFunMicroOLED.h: No such file or directory

The import statement was created automatically by the particle IDE, but I have edited it to try quote as well as angle brackets.

// This #include statement was automatically added by the Particle IDE.
#include "SparkFunMicroOLED.h"  // Include Micro OLED library

I have also cleared the cache.

The example code from the library works fine!

All very frustrating.

**Comment by Grahldg** [comment]
Hello and sorry for your frustration.  Are you adding the OLED library to the project as described [here](https://learn.sparkfun.com/tutorials/photon-oled-shield-hookup-guide?_ga=2.266073542.893584859.1532710721-2086957377.1530896610#using-the-particle-oled-library)?  If you just add the include statement without adding the library in the method described the compiler will not be able to find the file.  If you are continuing to experience issues after including the library you can get more immediate help by contacting our [Technical Support Team](https://www.sparkfun.com/technical_assistance).  If adding the library does resolve your issue please let me know and I will close this issue.
